"""user likes posts of other

Revision ID: a6641a611c87
Revises: de11993fb163
Create Date: 2020-04-06 14:30:49.784060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6641a611c87'
down_revision = 'de11993fb163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs_likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name=op.f('fk_blogs_likes_blog_id_blogs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blogs_likes_user_id_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_blogs_likes_read_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_comments_likes_read_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_likes_read_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_likes_read_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_comments_likes_read_time')
        batch_op.drop_column('last_blogs_likes_read_time')

    op.drop_table('blogs_likes')
    # ### end Alembic commands ###
